### ISSUE TITLE
can't setup Radiant

### ISSUE THREAD

**Issue by raksa** [radiant/radiant#400]
i'd love to try radiant, 
but spend almost 2 days still can't setup and running. 
when use heigh version of ruby get syntax deprecate, 
and after downgrade some gems not support for older version of ruby.
and after fix all then got error at "rake db:bootstrap" witch frozen gem issue
i want to ask you that have you ever tried to test installing your radiant from scratch recently.
because novice like me, ever can't use your radiant right now

**Comment by jume-dev** [comment]
We had the same issues and this is how we got it to work:
* ruby version 1.9.3
* make sure you have a mime-type gem with a version < 3, e.g. 2.99.2 already installed, because higher versions don't work with ruby < 2
* also downgrade your rubygems with gem update --system 1.8.25

Afterwards the whole installation process worked like in the wiki described
